#!/bin/bash

#TODO:
# - figure out why and when printer is spitting one blank file.
#
# -o page-set=even makes the printer spit one blank before printing
# looks like it has something to do with the duplex printing instructions


#Uncomment this to log to /var/log/cups/error_log
LOG() {
    echo "$@" >> /var/log/cups/error_log
}

LOG Starting duplexer job

# Output "Device Discovery" information on stdout:
if test "$#" = "0"
then
  echo 'direct duplex-print "Unknown" "(!) Manual_duplexer unit for linux. (!)"'
  exit 0
fi

#GET PRINTER AND USER FROM URI
#clip spaces
URI=${DEVICE_URI%% *}
# Extract the printer from the uri to which the job schould be sent from the URI.
# Clip the URI scheme (anything up to the first ':' character) and
# clip anything after the first '?' character
USE_PRINTER=${URI#*:}
USE_PRINTER=${USE_PRINTER%%\?*}

# Command line arguments
job="$1"
user="$2"
title="$3"
numcopies="$4"
options="$5"
filename="/var/spool/cups/duplex/$job.duplex"
if test -z "$6" ; then
  LOG "no filename, copying stdin to $filename"
  cat - >"$filename"
else
  LOG "copying $6 to $filename"
  cp "$6" "$filename"
fi


lp_args=
for opt in $options
do
	lp_args="$lp_args -o $opt"
done

page_count=$(pdfinfo "$filename" | grep Pages | awk '{print $2}')
LOG "page count: $page_count"

#if only one page, just send the printing command
if [ $(( $page_count )) -eq 1 ]; then
	LOG printing ONE page
	lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o collate=true -o orientation-requested=6 -t "$title"-onepage "$filename"

#if more than one pages, print odd pages first and show user interface
elif [ $(( $page_count )) -gt 1 ]; then
	LOG more than one page was sent. printing odd pages
	lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o page-set=odd -o collate=true -o outputorder=normal \
		-o orientation-requested=3 -t "$title"-odd "$filename"
	#show user interface
	if sudo -u $user zenity --question --title="$title" \
        --text="<big><b>Reinserte las hojas tal cual una vez finalizada la impresion y pulse Seguir.</b></big>" \
        --icon-name="document-print" \
	    --window-icon "/usr/share/manual_duplex_linux/printer.png"\
        --ok-label="Seguir" --cancel-label="Cancelar" --display=:0.0 --no-wrap ; then

	LOG printing even pages
	lp -s -d $USE_PRINTER -n "$numcopies" $lp_args -o page-set=even -o collate=true -o outputorder=reverse \
		-o orientation-requested=6 -t "$title"-even "$filename"


# UNCOMMENT IF CUPS-FILTERS VERSION IS BELOW 1.0.55
# Also SET your main printer as default printer
# SEE https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1340435
#        LOG PRINT ONE BLANK if needed
#        if [ `expr $page_count % 2` == 0 ]; then
#		LOG No need for blanks - pages are even
#        else
#		LOG spitting a blank - pages are odd
#		echo |  lp -s -t "$filename"-blank
#        fi


    else
        echo >&2 User abort
        rm "$filename"
        exit 0
    fi
fi

rm "$filename"
exit 0
